name: Prettier
on: [push]
jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/vishsanghishetty/gleb-cy-course
      - Default: ${{ github.gleb-cy-course }}
      - run: npm-install
      - run: npm run format
      - run: git status
      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        env:
          # github token is automatically injected by GH Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
