name: run prettier on repo
on: [push]
jobs:
  build:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vishsanghishetty/gleb-cy-course/@main
      - run: npm-install
      - run: npm run format
      - run: git status

      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        env:
          # github token is automatically injected by GH Action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
